<a href="https://colab.research.google.com/github/simplexityware/MScFE-WQU/blob/main/610_CRT_M1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MScFE 610 Econometics CRT M1

1. Write the CAPM the equation, specifying what each term means.

> The CAPM describes the relationship between systematic risk and expected return for assets(stocks in this exercise)

>> $E(R_i)=R_f+\beta_i(E(R_m)-R_f)$

> where:

>> $E(R_i)$ is the expected return on an $i$nvestment

>> $E(R_m)$ is the expected $m$arket return

>> $\beta_i$ is the systemic or market risk of the $i$nvestment

>> $R_f$ is the risk-free rate of return


2. Explain in words how the model explains the return of a stock.  

> The above equation can be simplified as follows:

>> $R_i=R_f+\beta_i(R_m-R_f)$

> where:

>> $R_i$ is the rate of return of the $i$nvestment

>> $R_m$ is the rate of return of the $m$arket

> Rearranging the above equation to provide an interpretation as a regression line called the $S$ecurity $M$arket $L$ine: 

>> $R_i - R_f = \alpha + \beta_i(R_m-R_f) + \epsilon$

> where:

>> $R_i - R_f$ is the $i$nvestment risk premium

>> $R_m - R_f$ is the $m$arket risk premium

> Therefore, the equation can be interpreted as: the risk premium of individual stock depends on its market risk, $\beta_i$ and the market risk premium, $(R_m-R_f)$. $\beta_i$, representing the slope of the preceding linear regression, measures the increase of the expected market risk premium as the individual stock's expected return increases and vice versa, ie when the former increases by 1%, the latter increases by $\beta_i$%  


3. Choose a stock.  Download 1 year worth of data of the adjusted closing price.

In [ ]:
import pandas_datareader.data as getData
import datetime as dt
# retrieving historical prices for APPLE stock from Yahoo!Finance for 14June20 to 14June21
dt_begdate = dt.datetime(2020, 6, 14) # 14th June 2020
dt_enddate = dt.datetime(2021, 6, 14) # 14th June 2021
df_aapl = getData.get_data_yahoo('AAPL', dt_begdate, dt_enddate) 
df_aapl # adjusted closing prices are on the last column below

                  High         Low  ...       Volume   Adj Close
Date                                ...
2020-06-15   86.419998   83.144997  ...  138808800.0   85.173584
2020-06-16   88.300003   86.180000  ...  165428800.0   87.430885
2020-06-17   88.849998   87.772499  ...  114406400.0   87.309204
2020-06-18   88.362503   87.305000  ...   96820400.0   87.343979
2020-06-19   89.139999   86.287498  ...  264476000.0   86.844833
...                ...         ...  ...          ...         ...
2021-06-08  128.460007  126.209999  ...   74403800.0  126.739998
2021-06-09  127.750000  126.519997  ...   56877900.0  127.129997
2021-06-10  128.190002  125.940002  ...   71186400.0  126.110001
2021-06-11  127.440002  126.099998  ...   53415300.0  127.349998
2021-06-14  129.876907  127.070000  ...   40691442.0  129.360001

[252 rows x 6 columns]

In [ ]:
!pip install mplfinance
import mplfinance as mpf
setup = dict(type='candle')
mpf.plot(df_aapl.iloc[-40:],ylabel='AAPL Stock Prices',**setup,width_adjuster_version='v0')


4. Compute the return from this series.

In [ ]:
# To compute the daily returns of AAPL stock using the time series above
#df_aapl['Returns'] = (df_aapl['Adj Close'][1:] - df_aapl['Adj Close'][:-1]) / df_aapl['Adj Close'][:-1]
#or the following ...
df_aapl['Returns'] = df_aapl['Adj Close'].diff()/df_aapl['Adj Close'].shift(1)
df_aapl

                  High         Low  ...   Adj Close   Returns
Date                                ...
2020-06-15   86.419998   83.144997  ...   85.173584       NaN
2020-06-16   88.300003   86.180000  ...   87.430885  0.026502
2020-06-17   88.849998   87.772499  ...   87.309204 -0.001392
2020-06-18   88.362503   87.305000  ...   87.343979  0.000398
2020-06-19   89.139999   86.287498  ...   86.844833 -0.005715
...                ...         ...  ...         ...       ...
2021-06-08  128.460007  126.209999  ...  126.739998  0.006672
2021-06-09  127.750000  126.519997  ...  127.129997  0.003077
2021-06-10  128.190002  125.940002  ...  126.110001 -0.008023
2021-06-11  127.440002  126.099998  ...  127.349998  0.009833
2021-06-14  129.876907  127.070000  ...  129.360001  0.015783

[252 rows x 7 columns]

 
5. Find the stockâ€™s beta from a financial website.

> 1.21          
> Reference: https://finance.yahoo.com/quote/AAPL?p=AAPL&.tsrc=fin-srch

6. Choose a benchmark, say the SP500.  Download 1 year worth of data of the adjusted closing price.  Make sure the time period matches for the benchmark and the stock.          
> 
> Reference: https://finance.yahoo.com/quote/%5EGSPC/history/

In [49]:
# retrieving historical prices and compute returns for S&P500 index from Yahoo!Finance for 14June20 to 14June21
df_sp500 = getData.get_data_yahoo('^GSPC', dt_begdate, dt_enddate)

7. Compute the return of this benchmark.

In [48]:
df_sp500['Returns'] = df_sp500['Adj Close'].diff()/df_sp500['Adj Close'].shift(1)
df_sp500

                   High          Low  ...    Adj Close   Returns
Date                                  ...
2020-06-15  3079.760010  2965.659912  ...  3066.590088       NaN
2020-06-16  3153.449951  3076.060059  ...  3124.739990  0.018962
2020-06-17  3141.159912  3108.030029  ...  3113.489990 -0.003600
2020-06-18  3120.000000  3093.510010  ...  3115.340088  0.000594
2020-06-19  3155.530029  3083.110107  ...  3097.739990 -0.005649
...                 ...          ...  ...          ...       ...
2021-06-08  4236.740234  4208.410156  ...  4227.259766  0.000175
2021-06-09  4237.089844  4218.740234  ...  4219.549805 -0.001824
2021-06-10  4249.740234  4220.339844  ...  4239.180176  0.004652
2021-06-11  4248.379883  4232.250000  ...  4247.439941  0.001948
2021-06-14  4248.310059  4234.069824  ...  4235.359863 -0.002844

[252 rows x 7 columns]

The Yahoo Finance ticker ^IRX provides the official discount rate of the 13 week US Treasury Bill.

> $R_{daily} = (1 + R_{13week})^{13*5/252} - 1$

where:

> $R_{daily}$ is the effective risk-free daily rate of return

> $R_{13week}$ is the value obtained from Yahoo Finance ticker ^IRX divided by 100


8. Formulate the CAPM using your stockâ€™s return, the benchmark return, and a risk-free rate.

In [ ]:
df_13wkTBill = getData.get_data_yahoo('^IRX', dt_begdate, dt_enddate)
df_13wkTBill

In [ ]:
df_13wkTBill['Risk-Free'] = (1 + df_13wkTBill['Adj Close'] / 100) ** (13 * 5 / 252) - 1
df_13wkTBill

             High    Low   Open  Close  Volume  Adj Close  Risk-Free
Date
2020-06-15  0.163  0.155  0.158  0.155     0.0      0.155   0.000400
2020-06-16  0.163  0.153  0.153  0.160     0.0      0.160   0.000412
2020-06-17  0.165  0.160  0.160  0.165     0.0      0.165   0.000425
2020-06-18  0.148  0.140  0.148  0.140     0.0      0.140   0.000361
2020-06-19  0.148  0.140  0.143  0.143     0.0      0.143   0.000369
...           ...    ...    ...    ...     ...        ...        ...
2021-06-08  0.020  0.020  0.020  0.020     0.0      0.020   0.000052
2021-06-09  0.020  0.020  0.020  0.020     0.0      0.020   0.000052
2021-06-10  0.020  0.020  0.020  0.020     0.0      0.020   0.000052
2021-06-11  0.018  0.015  0.018  0.018     0.0      0.018   0.000046
2021-06-14  0.020  0.015  0.018  0.015     0.0      0.015   0.000039

[250 rows x 7 columns]

In [ ]:
#from pandas.stats.api import ols
import statsmodels.api as sm
df_y = df_aapl['Returns'] - df_13wkTBill['Risk-Free']
df_x = df_sp500['Returns'] - df_13wkTBill['Risk-Free']
#result = ols(y=df_y, x=df_x)
results = sm.OLS(df_y[200:], df_x[200:]).fit()
print(results.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.591
Model:                            OLS   Adj. R-squared (uncentered):              0.583
Method:                 Least Squares   F-statistic:                              73.59
Date:                Mon, 14 Jun 2021   Prob (F-statistic):                    1.83e-11
Time:                        21:34:08   Log-Likelihood:                          171.57
No. Observations:                  52   AIC:                                     -341.1
Df Residuals:                      51   BIC:                                     -339.2
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             1.4892      0.174      8.578      0.000       1.141       1.838
==============================================================================
Omnibus:                        0.777   Durbin-Watson:                   2.138
Prob(Omnibus):                  0.678   Jarque-Bera (JB):                0.258
Skew:                          -0.126   Prob(JB):                        0.879
Kurtosis:                       3.236   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Therefore, $\beta_{AAPL}$ is 1.4892 as compared to 1.21 (5 year) obtained from Yahoo Finance.